# This workflow will install Python dependencies and run tests

name: Test Projects on env release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run:  pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Test with pytest
      env:
        LOGIN1: ${{secrets.LOGIN1}}
        FULLNAME1: ${{secrets.FULLNAME1}}
        PASS1: ${{secrets.ReleasePass1}}
        START_URL: ${{secrets.ReleaseStartUrl}}
        IS_HEADLESS: "true"
      run: pytest tests/gui/projects
